# -----------------------------
# Stable v1 Ingress
# -----------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-shop-ingress
  namespace: canary-deployment
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # Optional
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: online-shop-v1   # <-- Stable Service
            port:
              number: 80

---

# -----------------------------
# Canary v2 Ingress
# -----------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-shop-canary-ingress
  namespace: canary-deployment
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"  # 100% traffic to canary (adjust as needed)
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: online-shop-v2   # <-- Canary Service
            port:
              number: 80
